### ISSUE TITLE
No longer works with Beta 4

### ISSUE THREAD

**Issue by misbell** [StephenMcMillan/Dub-Dub-Do#1]
![2019-07-20 at 8 18 PM](https://user-images.githubusercontent.com/356572/61585539-81bb7400-ab2b-11e9-91f4-e3c81c8c0d17.jpg)

**Comment by fabstu** [comment]
`didChange -> willChange` probably.

**Comment by misbell** [comment]
that was it :-)

**Comment by StephenMcMillan** [comment]
The demo now works with Xcode 11.5. See #5 🙂
