### ISSUE TITLE
fixed 'willchange' issue

### ISSUE THREAD

**Issue by misbell** [StephenMcMillan/Dub-Dub-Do#2]
now the code compiles and runs but nothing appears onscreen. 

these deprecations appear:

![2019-07-25 at 6 16 PM](https://user-images.githubusercontent.com/356572/61912560-78a21c80-af08-11e9-97eb-e4f88a8415f8.jpg)

**Comment by StephenMcMillan** [comment]
The demo now works with Xcode 11.5. See #5 🙂
